//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posh_TRPT_Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posh_TRPT_Utility.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTECTED CONTROLLER ACCESSED.
        /// </summary>
        public static string Accessed {
            get {
                return ResourceManager.GetString("Accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Astric {
            get {
                return ResourceManager.GetString("Astric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiDtaSendNewData.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer.
        /// </summary>
        public static string Bearer {
            get {
                return ResourceManager.GetString("Bearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://posh-trpt-qa.chetu.com/api/.
        /// </summary>
        public static string DbProdURL {
            get {
                return ResourceManager.GetString("DbProdURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultConnection.
        /// </summary>
        public static string DefaultConnection {
            get {
                return ResourceManager.GetString("DefaultConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE CONTROLLER ACCESSED.
        /// </summary>
        public static string EmployeeAccessed {
            get {
                return ResourceManager.GetString("EmployeeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration/GetDriverMasterDetailsById.
        /// </summary>
        public static string GetDriverMasterDetailsById {
            get {
                return ResourceManager.GetString("GetDriverMasterDetailsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error!.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44349.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWToken.
        /// </summary>
        public static string JWToken {
            get {
                return ResourceManager.GetString("JWToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44349/api/.
        /// </summary>
        public static string LocalUrl {
            get {
                return ResourceManager.GetString("LocalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posh-TRPT.
        /// </summary>
        public static string Posh_TRPT {
            get {
                return ResourceManager.GetString("Posh-TRPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration/GetCountries.
        /// </summary>
        public static string RegistrationGetCountries {
            get {
                return ResourceManager.GetString("RegistrationGetCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration/GetAllDriversBasicDetails.
        /// </summary>
        public static string RegistrationGetDrivers {
            get {
                return ResourceManager.GetString("RegistrationGetDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKJGSAHFOLKBDLADADA9-80297aBCFADAPKDK98UIH9UHD23D33#DADAF.
        /// </summary>
        public static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44349.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
