//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posh_TRPT_Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DriverRegisterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverRegisterResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posh_TRPT_Utility.Resources.DriverRegisterResource", typeof(DriverRegisterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address detaild deleted successfully!.
        /// </summary>
        public static string AddressDeleted {
            get {
                return ResourceManager.GetString("AddressDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address could not delete!.
        /// </summary>
        public static string AddressDeleteFailed {
            get {
                return ResourceManager.GetString("AddressDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details added successfully!.
        /// </summary>
        public static string AddressDetailAdded {
            get {
                return ResourceManager.GetString("AddressDetailAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details found!.
        /// </summary>
        public static string AddressDetailFound {
            get {
                return ResourceManager.GetString("AddressDetailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details add failed!.
        /// </summary>
        public static string AddressDetailsAddFailed {
            get {
                return ResourceManager.GetString("AddressDetailsAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details deleted successfully!.
        /// </summary>
        public static string AddressDetailsDeleted {
            get {
                return ResourceManager.GetString("AddressDetailsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details updated successfully!.
        /// </summary>
        public static string AddressDetailsUpdated {
            get {
                return ResourceManager.GetString("AddressDetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address details update failed!.
        /// </summary>
        public static string AddressDetailUpdateFailed {
            get {
                return ResourceManager.GetString("AddressDetailUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found!.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details added successfully!.
        /// </summary>
        public static string DetailsAdded {
            get {
                return ResourceManager.GetString("DetailsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details already added!.
        /// </summary>
        public static string DetailsAlreadyAdded {
            get {
                return ResourceManager.GetString("DetailsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver details updated successfully!.
        /// </summary>
        public static string DetailsUpdated {
            get {
                return ResourceManager.GetString("DetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details updation failed..
        /// </summary>
        public static string DetailUpdateFails {
            get {
                return ResourceManager.GetString("DetailUpdateFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver documents added successfully!.
        /// </summary>
        public static string DocumentAdded {
            get {
                return ResourceManager.GetString("DocumentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver documents deleted successfully!.
        /// </summary>
        public static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents deletion failed!.
        /// </summary>
        public static string DocumentDeleteFailed {
            get {
                return ResourceManager.GetString("DocumentDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver documents found!.
        /// </summary>
        public static string DocumentFound {
            get {
                return ResourceManager.GetString("DocumentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver documents not found!.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents uploading failed!.
        /// </summary>
        public static string DocumentsAddFailed {
            get {
                return ResourceManager.GetString("DocumentsAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents update failed!.
        /// </summary>
        public static string DocumentsUpdateFailed {
            get {
                return ResourceManager.GetString("DocumentsUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver documents updated successfully!.
        /// </summary>
        public static string DocumentUpdated {
            get {
                return ResourceManager.GetString("DocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver deleted successfully!.
        /// </summary>
        public static string DriverDelete {
            get {
                return ResourceManager.GetString("DriverDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver deletion failed..
        /// </summary>
        public static string DriverDeleteFailed {
            get {
                return ResourceManager.GetString("DriverDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driver details not found!.
        /// </summary>
        public static string DriverDetailNotFound {
            get {
                return ResourceManager.GetString("DriverDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driver details found successful!.
        /// </summary>
        public static string DriverDetailsFound {
            get {
                return ResourceManager.GetString("DriverDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somthing went wrong!.
        /// </summary>
        public static string DriverStatusUpdateFailed {
            get {
                return ResourceManager.GetString("DriverStatusUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver status updated successfully!.
        /// </summary>
        public static string DriverStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("DriverStatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select term and conditions!.
        /// </summary>
        public static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login again!.
        /// </summary>
        public static string UserRelogin {
            get {
                return ResourceManager.GetString("UserRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle delete failed!.
        /// </summary>
        public static string VehicleDeleteFailed {
            get {
                return ResourceManager.GetString("VehicleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details found successfully!.
        /// </summary>
        public static string VehicleDetailFound {
            get {
                return ResourceManager.GetString("VehicleDetailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details not found!.
        /// </summary>
        public static string VehicleDetailNotFound {
            get {
                return ResourceManager.GetString("VehicleDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details added successfully!.
        /// </summary>
        public static string VehicleDetailsAdded {
            get {
                return ResourceManager.GetString("VehicleDetailsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details adding failed!.
        /// </summary>
        public static string VehicleDetailsAddFailed {
            get {
                return ResourceManager.GetString("VehicleDetailsAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details deleted successfully!.
        /// </summary>
        public static string VehicleDetailsDeteted {
            get {
                return ResourceManager.GetString("VehicleDetailsDeteted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vechicle details updated successfully!.
        /// </summary>
        public static string VehicleDetailsUpdated {
            get {
                return ResourceManager.GetString("VehicleDetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details update failed!.
        /// </summary>
        public static string VehicleDetailsUpdateFailed {
            get {
                return ResourceManager.GetString("VehicleDetailsUpdateFailed", resourceCulture);
            }
        }
    }
}
