//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posh_TRPT_Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posh_TRPT_Utility.Resources.GlobalResourceFile", typeof(GlobalResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account link created successfully.
        /// </summary>
        public static string AccountLinkCreated {
            get {
                return ResourceManager.GetString("AccountLinkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account link creation failed.
        /// </summary>
        public static string AccountLinkCreationFailed {
            get {
                return ResourceManager.GetString("AccountLinkCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \assets\verified.html.
        /// </summary>
        public static string AssetsHtml {
            get {
                return ResourceManager.GetString("AssetsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking request has been accepted.
        /// </summary>
        public static string BookingStatusAccepted {
            get {
                return ResourceManager.GetString("BookingStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking has been cancelled.
        /// </summary>
        public static string BookingStatusCancelled {
            get {
                return ResourceManager.GetString("BookingStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingStatusCompleted.
        /// </summary>
        public static string BookingStatusCompleted {
            get {
                return ResourceManager.GetString("BookingStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking request has been declined.
        /// </summary>
        public static string BookingStatusDeclined {
            get {
                return ResourceManager.GetString("BookingStatusDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the box!.
        /// </summary>
        public static string CheckBoxNotChecked {
            get {
                return ResourceManager.GetString("CheckBoxNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create payment intent response data found.
        /// </summary>
        public static string CreatePaymentIntentResponseDataFound {
            get {
                return ResourceManager.GetString("CreatePaymentIntentResponseDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create payment intent response data not found.
        /// </summary>
        public static string CreatePaymentIntentResponseDataNotFound {
            get {
                return ResourceManager.GetString("CreatePaymentIntentResponseDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer created successfully!.
        /// </summary>
        public static string CustomerCreated {
            get {
                return ResourceManager.GetString("CustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details found successfully.
        /// </summary>
        public static string CustomerDetailsFound {
            get {
                return ResourceManager.GetString("CustomerDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details not found.
        /// </summary>
        public static string CustomerDetailsNotFound {
            get {
                return ResourceManager.GetString("CustomerDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer registration failed!.
        /// </summary>
        public static string CustomerRegistrationFailed {
            get {
                return ResourceManager.GetString("CustomerRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not found or deleted!.
        /// </summary>
        public static string DocumentIsDeleted {
            get {
                return ResourceManager.GetString("DocumentIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document update failed!.
        /// </summary>
        public static string DocumentUpdateFailed {
            get {
                return ResourceManager.GetString("DocumentUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document updated successfully!.
        /// </summary>
        public static string DocumentUpdateSuccess {
            get {
                return ResourceManager.GetString("DocumentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents upload failed!.
        /// </summary>
        public static string DocumentUploadedFailed {
            get {
                return ResourceManager.GetString("DocumentUploadedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents uploaded successfully!.
        /// </summary>
        public static string DocumentUploadedSuccess {
            get {
                return ResourceManager.GetString("DocumentUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver details found successfully.
        /// </summary>
        public static string DriverDetailsFound {
            get {
                return ResourceManager.GetString("DriverDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver details not found.
        /// </summary>
        public static string DriverDetailsNotFound {
            get {
                return ResourceManager.GetString("DriverDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver payout status is false.
        /// </summary>
        public static string DriverPayoutStatusFalse {
            get {
                return ResourceManager.GetString("DriverPayoutStatusFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver profile created successfully!.
        /// </summary>
        public static string DriverProfileCreated {
            get {
                return ResourceManager.GetString("DriverProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver profile creation failed!.
        /// </summary>
        public static string DriverProfileCreationFailed {
            get {
                return ResourceManager.GetString("DriverProfileCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers available.
        /// </summary>
        public static string DriversAvailable {
            get {
                return ResourceManager.GetString("DriversAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers not available.
        /// </summary>
        public static string DriversNotAvailable {
            get {
                return ResourceManager.GetString("DriversNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code didn&apos;t match! Try re-register!.
        /// </summary>
        public static string InValidVerificationCode {
            get {
                return ResourceManager.GetString("InValidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EphemeralKey Found.
        /// </summary>
        public static string KeyFound {
            get {
                return ResourceManager.GetString("KeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EphemeralKey Not Found.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model State!.
        /// </summary>
        public static string ModelStateInvalid {
            get {
                return ResourceManager.GetString("ModelStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment method found..
        /// </summary>
        public static string NoPaymetMethodFound {
            get {
                return ResourceManager.GetString("NoPaymetMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is null or empty.
        /// </summary>
        public static string NullValve {
            get {
                return ResourceManager.GetString("NullValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was cancelled by user.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed failed!.
        /// </summary>
        public static string PasswordChangedUnSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method found.
        /// </summary>
        public static string PaymetMethodFound {
            get {
                return ResourceManager.GetString("PaymetMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout status of connect account is false.
        /// </summary>
        public static string PayoutStatusConnectAccountFalse {
            get {
                return ResourceManager.GetString("PayoutStatusConnectAccountFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout status of connect account is true.
        /// </summary>
        public static string PayoutStatusConnectAccountTrue {
            get {
                return ResourceManager.GetString("PayoutStatusConnectAccountTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilePhotos.
        /// </summary>
        public static string ProfilePic {
            get {
                return ResourceManager.GetString("ProfilePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide mobile number!.
        /// </summary>
        public static string ProvideMobileNumber {
            get {
                return ResourceManager.GetString("ProvideMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notification sent successfully.
        /// </summary>
        public static string PushNotification {
            get {
                return ResourceManager.GetString("PushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send the push notification.
        /// </summary>
        public static string PushNotificationFailed {
            get {
                return ResourceManager.GetString("PushNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup payment intent response data found.
        /// </summary>
        public static string SetupIntentResponseDataFound {
            get {
                return ResourceManager.GetString("SetupIntentResponseDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup payment intent response data not found.
        /// </summary>
        public static string SetupIntentResponseDataNotFound {
            get {
                return ResourceManager.GetString("SetupIntentResponseDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tips or Review has been given.
        /// </summary>
        public static string TipsReviewNotProvided {
            get {
                return ResourceManager.GetString("TipsReviewNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips or Review has been added successfully.
        /// </summary>
        public static string TipsReviewSuccess {
            get {
                return ResourceManager.GetString("TipsReviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadDocuments.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s booking detail found successfully!.
        /// </summary>
        public static string UserBookingDetaillsFound {
            get {
                return ResourceManager.GetString("UserBookingDetaillsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s booking detail not found!.
        /// </summary>
        public static string UserBookingDetaillsNotFound {
            get {
                return ResourceManager.GetString("UserBookingDetaillsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists!.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exists!.
        /// </summary>
        public static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
